//> error "expected ; at"

func foo() -> void {}

func main() {
	foo()
}
